Repository prasathmani/tinyfilemanager, pull requests merged in 2019-07, with the labels that each got.

#175 Add Save by ajax request
  tinyfilemanager.php
Labels: Feature, enhancement

#179 Improve Multilanguage Support
  tinyfilemanager.php
  translation.json
Labels: enhancement

#182 Updated italian translation
  translation.json
Labels: enhancement

#193 Update translation.json, add czech translation
  translation.json
Labels: Feature

#194 Update tinyfilemanager.php, add words for translation
  tinyfilemanager.php
Labels: Request

#196 Fix spelling of "copyied" after copying file
  tinyfilemanager.php
Labels: Request
