Repository prasathmani/tinyfilemanager, pull requests merged in 2019-05, with the labels that each got.

#151 Update translation.json
  translation.json
Labels: enhancement

#162 add vietnamese language
  translation.json
Labels: enhancement

#156 Add Custom Title and Favicon options
  tinyfilemanager.php
Labels: Request

#178 Basic IP white- and blacklisting
  .editorconfig
  tinyfilemanager.php
Labels: enhancement

#176 Add Arabic Translation
  translation.json
Labels: Feature

#174 Add Hebrew Language
  translation.json
Labels: Feature
